<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Support\Facades\Session;
use Closure;
class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
//    protected function redirectTo($request)
//    {
//        if (! $request->expectsJson()) {
//            return route('login');
//        }
//    }
        public function handle($request, Closure $next, ...$guards)
        {
            if (Session::has('id')) {
                return $next($request);
            }
            return redirect()->route('layer.loginAdmin')->with('error','You must login');
//            return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub
        }
}
